name: build-github-runner-container-images
on:
  workflow_dispatch:
  
jobs:
  build-linux-github-runner-container-image:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Linux Container Image Build 
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:container-image/linux"
          push: false
          tags: bgrozoiughracr02.azurecr.io/github-runner/linux

  build-windows-github-runner-container-image:
    runs-on: windows-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3

      - run: |
          docker build --tag bgrozoiughracr02.azurecr.io/github-runner/windows .\container-image\windows