name: build-github-runner-container-images
on:
  push:
    branches:
      - "feature/ghr-runner-docker-image"
jobs:
  build-linux-github-runner-container-image:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Linux Container Image Build 
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:container-image/linux"
          push: false
          tags: docker-github-runner-linux:latest

  build-windows-github-runner-container-image:
    runs-on: windows-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3

      - run: |
          docker build --tag docker-github-runner-windows .\container-image\windows