name: Demonstrative workflow for self-hosted runners
on:
  push:
    branches: [ demo-features/* ]
  workflow_dispatch:

jobs:
  demo-self-hosted-large-file:
    runs-on: [self-hosted, linux]
    permissions:
      contents: read
    steps:
      - run: |
          df -h
          curl https://releases.ubuntu.com/22.04.1/ubuntu-22.04.1-live-server-amd64.iso -o file.iso
          df -h
          tar -czvf file.tar.gz file.iso
          df -h
          rm -f file.iso
          rm -f file.tar.gz
          df -h

  demo-self-hosted-execute-perms:
    needs: [demo-self-hosted-large-file]
    runs-on: [self-hosted, linux]
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3