name: Deploy the Azure infrastructure for GitHub runners
on:
  push:
    branches: [feature/azure-infra-for-ghr]
  workflow_dispatch:

jobs:
  foundation:
    runs-on: [self-hosted, linux]
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'feature/azure-infra-for-ghr'

      - uses: azure/login@v1
        name: OIDC Login to Customer Tenant
        with:         
          tenant-id: ${{ secrets.TENANT_ID }}
          client-id: ${{ secrets.CLIENT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
          enable-AzPSSession: true