name: Example workflow self-hosted
on:
  push:
    branches: [ candidate-fix/container-app-exit-code-137 ]
  workflow_dispatch:

jobs:
  demo-self-hosted:
    runs-on: [self-hosted, linux]
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3

      - run: |
          df -h
          curl https://releases.ubuntu.com/22.04.1/ubuntu-22.04.1-live-server-amd64.iso -o file.iso
          df -h
          tar -czvf file.tar.gz file.iso
          df -h